build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 70 # Lo subiste a 70, perfecto para dar aire a los Composables
  LongParameterList:
    active: true
    functionThreshold: 8 # Umbral de 8, ideal para evitar agrupar todo prematuramente

naming:
  active: true
  FunctionNaming:
    active: true
    # Agregamos soporte para funciones que empiezan con mayúscula (Composables)
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*' # Eliminamos el "_" inicial, no es estándar en Kotlin

style:
  active: true
  MagicNumber:
    active: true
    # Números comunes que no deben marcarse como error
    ignoreNumbers: ['-1', '0', '1', '2', '8', '16', '32', '100', '200', '400', '500']
    # Ignoramos MagicNumbers en propiedades y anotaciones (Crucial para @Preview)
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreLocalVariableDeclaration: true

exceptions:
  TooGenericExceptionCaught:
    active: true
    # Tu regex es correcto, pero incluimos CancellationException como recomendación
    allowedExceptionNameRegex: '^(Exception|RuntimeException|CancellationException)$'